name: deploy-containerApp
on:
  push:
    branches:
      - main
    paths:
      - 'container/**'

defaults:
  run:
    working-directory: container

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: s3 sync container/dist s3://cmfe-dashboard/container/lastest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}