name: deploy-marketingApp
on:
  push:
    branches:
      - main
    paths:
      - 'packages/marketing/**'
      - './github/workflows/**'

defaults:
  run:
    working-directory: packages/marketing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ## CREAR BUNDLE
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}
      ## CREAR BUNDLE --FIN

      ## SUBO BUNDLE A S3
      - uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: s3 sync packages/marketing/dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/marketing/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ## SUBO BUNDLE A S3 --FIN

      ## CREA INVALIDATION PARA QUE CF SIRVA SIEMPRE LA ÚLTIMA VERSION DE NUESTRA APP.
      - uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: cloudfront create-invalidation --distribution-id ${{secrets.AWS_DISTRIBUTION_ID}} --paths "/marketing/latest/index.html"
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    ## CREA INVALIDATION PARA QUE CF SIRVA SIEMPRE LA ÚLTIMA VERSION DE NUESTRA APP. --FIN
